receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  azuremonitor:
    connection_string: "${APPLICATIONINSIGHTS_CONNECTION_STRING}"
  logging:
    loglevel: debug

processors:
  batch:

  filter:
    logs:
      log_record:
        - 'IsMatch(instrumentation_scope.name, "Microsoft\\\\..*")'
        - 'IsMatch(instrumentation_scope.name, "System\\\\..*")'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, logging]
    logs:
      receivers: [otlp]
      processors: [batch, filter]
      exporters: [azuremonitor, logging]