receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: {}
  filter/drop_framework_logs:
    logs:
      exclude:
        match_type: regexp
        attributes:
          - key: log.category
            value: ^(Microsoft|System)\.
          - key: logger.category
            value: ^(Microsoft|System)\.
  filter/keep_app_severity:
    logs:
      include:
        match_type: strict
        severity_texts: [INFO, WARN, ERROR, FATAL]

exporters:
  azuremonitor:
    connection_string: ${APPLICATIONINSIGHTS_CONNECTION_STRING}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [filter/drop_framework_logs, filter/keep_app_severity, batch]
      exporters: [azuremonitor]
  telemetry:
    logs:
      level: "info"
